POST http://localhost:3333/polls
Content-Type: application/json

{
    "title": "Vasco é o melhor?",
    "options": ["Sim", "Claro", "Com certeza"]
}

###

GET http://localhost:3333/polls/aba03d08-ca75-4adb-a653-4d3a863e386f

###

POST http://localhost:3333/polls/aba03d08-ca75-4adb-a653-4d3a863e386f/votes
Content-Type: application/json

{
    "pollOptionId": "df11f6e7-9c47-4e7e-8bd7-c56d02cd0d55"
}